spring.application.name=MR_Backend_WH

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.properties.hibernate.default_schema=manuel_romero
spring.datasource.driver-class-name=org.postgresql.Driver

# update, create, create-drop, validate, none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT / OAuth properties (usarlas desde template_google TokenProvider)
app.jwt.secret=replace_with_a_strong_secret_key_at_least_32_chars
app.jwt.expiration.minutes=180

# OAuth2 client (Google) - explicit values restored
spring.security.oauth2.client.registration.google.client-id=385759181260-sr4onmvkrfe15vpvsqd9n0ivjmhmhka6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}